# Generated by Django 3.1.13 on 2021-09-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20210914_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pass_id',
            field=models.CharField(default=1, editable=False, max_length=20),
        ),
    ]
